### ISSUE TITLE
请问如何在UE5中使用？

### ISSUE THREAD

**Issue by LiXiaoRan** [ljason1993/WebSocketServer-unreal#3]
请问如何在UE5中使用？

**Comment by ljason1993** [comment]
UE5我没有测试过哦，最近没时间呀

**Comment by ljason1993** [comment]
原地直升ue5即可，没有问题，我测试了

**Comment by LiXiaoRan** [comment]
> 原地直升ue5即可，没有问题，我测试了

哈哈哈，的确没问题，我也用了忘了回复了

**Comment by ljason1993** [comment]
> > 原地直升ue5即可，没有问题，我测试了
> 
> 哈哈哈，的确没问题，我也用了忘了回复了

哈没事，那天正好我需要工程转ue5，捎带手测了一下
